version: "3.7"
services:
  datascience-demo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_TOKEN=rta
      - JULIA_VERSION=1.7.3
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    ports:
      - 8888:8888
    container_name: datascience